# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#whether modelling using the quadratic Equation
a = 5
b = 4
c = 6
x = 4.5
y = a *x *x + b * x + c
print('The value of y is ',y)